workflows: Test CI

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -13,43 +13,43 @@ on:
       - prod
 
 jobs:
-  build-and-test:
-    runs-on: ubuntu-latest
+  # build-and-test:
+  #   runs-on: ubuntu-latest
 
-    steps:
-    - uses: actions/checkout@v2
-      with:
-        fetch-depth: 0  # Fetch all history so that all branches are available
+  #   steps:
+  #   - uses: actions/checkout@v2
+  #     with:
+  #       fetch-depth: 0  # Fetch all history so that all branches are available
 
-    - name: Set up Python 3.11.9
-      uses: actions/setup-python@v2
-      with:
-        python-version: 3.11.9
+  #   - name: Set up Python 3.11.9
+  #     uses: actions/setup-python@v2
+  #     with:
+  #       python-version: 3.11.9
 
-    - name: Install dependencies
-      run: |
-        python -m pip install --upgrade pip
-        pip install -r requirements.txt
-        pip install flake8 pylint
+  #   - name: Install dependencies
+  #     run: |
+  #       python -m pip install --upgrade pip
+  #       pip install -r requirements.txt
+  #       pip install flake8 pylint
 
-    - name: Run linting
-      run: |
-        flake8 . || echo "Linting errors detected"
-        pylint */.py || echo "Pylint warnings/errors detected"
+  #   - name: Run linting
+  #     run: |
+  #       flake8 . || echo "Linting errors detected"
+  #       pylint */.py || echo "Pylint warnings/errors detected"
 
-    - name: Run unit tests
-      run: |
-        python -m unittest discover -s tests || echo "Test failures detected"
+  #   - name: Run unit tests
+  #     run: |
+  #       python -m unittest discover -s tests || echo "Test failures detected"
 
-    - name: Initialize CodeQL
-      uses: github/codeql-action/init@v2
-      with:
-        languages: python
+  #   - name: Initialize CodeQL
+  #     uses: github/codeql-action/init@v2
+  #     with:
+  #       languages: python
 
-    - name: Perform CodeQL analysis
-      uses: github/codeql-action/analyze@v2
-      with:
-        languages: python
+  #   - name: Perform CodeQL analysis
+  #     uses: github/codeql-action/analyze@v2
+  #     with:
+  #       languages: python
 
   # Push to staging after successful tests on dev
   push-to-staging:
@@ -92,7 +92,7 @@ jobs:
     - name: Push changes to prod
       run: |
         git checkout prod || git checkout -b prod
-        git merge staging
+        git merge origin/staging
         git push origin prod
 
   # Deploy to Vercel after successful tests on prod
